import type { Metadata } from "next";
import { Geist, Geist_Mono, Luckiest_Guy } from "next/font/google";
import "./globals.css";

// Geist Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Luckiest Guy font
const luckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  weight: "400", // Luckiest Guy only has one weight
  variable: "--font-luckiest-guy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={luckiestGuy.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} font-luckiest`}>
        {children}
      </body>
    </html>
  );
}
